app:
  env: dev
  name: go-mall
  log:
    path: "./storage/logs/go-mall.log"
    max_size: 100
    max_age: 60
  pagination:
    default_size: 20
    max_size: 100
database:
  type: mysql
  dsn: "reserved"
  maxopen: 100
  maxidle: 10
  maxlifetime: 300