app:
  env: dev
  name: go-mall
  log:
    path: "./storage/logs/go-mall.log"
    max_size: 100
    max_age: 60
  pagination:
    default_size: 20
    max_size: 100
database:
  master:
    type: mysql
    dsn: root:superpass@tcp(localhost:30306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000 # 300s 内可复用
  slave:
    type: mysql
    dsn: root:superpass@tcp(localhost:30306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000

redis: # 记得更改成自己的连接配置
  addr: 127.0.0.1:31379
  password: 123456
  pool_size: 10
  db: 0