app:
  env: prod
  name: go-mall
  log:
    path: "./storage/logs/go-mall.log"
    max_size: 100
    max_age: 60
database:
  type: mysql
  dsn: "reserved"
  maxopen: 100
  maxidle: 10
  maxlifetime: 300